---
functional:
  - Пользователь должен иметь возможность регистрации на сайте через электронную почту 
  - Пользователь должен иметь возможность регистрации на сайте через GitHub
  - Пользователь должен иметь возможность авторизации
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность выбирать подходящий ему уровень игры
  - Пользователь должен иметь возможность выбирать язык игры
  - Пользователь должен иметь возможность выбирать тип игры (с другими пользователями, с другом, с ботом)
  - Пользователь должен иметь возможность выбирать продолжительность игры
  - Пользователь должен иметь возможность проверять свое решение (кнопка "Check")
  - Пользователь должен иметь возможность просматривать историю сыгранных матчей
  - Пользователь должен иметь возможность видеть код соперника в реальном времени
  - Пользователь должен иметь возможность писать в чат сопернику и зрителям
  - Пользователь должен иметь возможность выйти из игры, нажав кнопку "Back to home"
  - Пользователь должен иметь возможность зайти в игру в качестве зрителя
  - Пользователь должен иметь возможность просматривать свой рейтинг и таблицу рейтинга других игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен иметь справочный раздел для пользователя с правилами игры
  - Сайт должен иметь заметный блок на главной странице сайта или в футере, где обозначены все доступные для игры языки
  - На сайте должна быть форма обратной связи
  - Пользователь должен иметь возможность выбрать русский язык для сайта
